trigger:
- main

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
    Python310:
      python.version: '3.10'
  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-pabot
          pip install robotframework-seleniumlibrary
          pip install webdriver_manager
          pip install webdrivermanager
          pip install selenium
  displayName: 'Install dependencies12'


- powershell: robot $(System.DefaultWorkingDirectory)/RobotFramework/TC1.robot
  displayName: 'Run Robot Framework Tests'
    
