trigger:
- main

pool:
  vmImage: 'windows-latest'

strategy:
  matrix:
    Python310:
      python.version: '3.10'
  maxParallel: 1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UsePythonVersion@0
  inputs: 
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: pip install robotframework
          pip install robotframework-pabot
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager
          pip install selenium
          pip install rpaframework 
  displayName: 'Install dependencies'

- powershell: robot **/TC1.robot
  displayName: 'Run Robot Scripts'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: outputxunit.xml
    searchFolder: 'D:\a\1\s\'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results outputxunit.xml'