trigger:
- main

pool:
  vmImage: 'windows-latest'

strategy:
  matrix:
    Python310:
      python.version: '3.10'
  maxParallel: 1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UsePythonVersion@0
  inputs: 
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: 
          pip install robotframework
          pip install robotframework-pabot
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager
          pip install selenium
          # pip install rpaframework-aws
          # pip install rpaframework
  displayName: 'Install dependencies12'

  - channels:
      - conda-forge
  - dependencies:
    - python=3.10
    - pip=20.1
    - pip:
        - rpaframework==14.1.1
    displatName:  'install RPA framework'

- powershell: robot $(System.DefaultWorkingDirectory)/RobotFramework/TC1.robot
  displayName: 'Run Robot Framework Tests'
    