# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

jobs:
  - job: 'Test'
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        Python310:
          python.version: '3.10'
      maxParallel: 1

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-selenium2library
        pip install rpaframework
        Pip install selenium
        pip install webdriver-manager
        pip install webdrivermanager
        npm install chromedriver
        
      displayName: 'Install dependencies'

    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/C:\Users\NISHITA-PC\PycharmProjects\RobotFramework\RobotFramework\TC1.robot'