# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-selenium2library
        pip install rpaframework
        Pip install selenium
        pip install webdriver-manager
        pip install webdrivermanager
        npm install chromedriver
        
        displayName: 'Install dependencies'

    - powershell: 
        Write-Host "Robot Framework tests"
        robot -x 'outputxunit.xml' -t 'Your Test' '$(Build.SourcesDirectory)\[YourProjectName]\tests\.'
    failOnStderr: true
    displayName: 'Run Robot Framework Tests'
    continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      continueOnError: true
      inputs:
          testResultsFiles: outputxunit.xml
